export const ROUTES_APP = {
    app: "/app",
    company_selection: "/company-selection",
    source: "/source",
    promotions: "/promotions",
    discount: "/discount",
    store: "/store",
}
export const ROUTES = {
    administracion: ROUTES_APP.app + ROUTES_APP.source + "/administracion",
    atenciones: ROUTES_APP.app + ROUTES_APP.source + "/atenciones",
    setting: ROUTES_APP.app + ROUTES_APP.source + "/setting",
    settingOrganization: ROUTES_APP.app + ROUTES_APP.source + "/settingOrganization",
    agenda: ROUTES_APP.app + ROUTES_APP.source + "/agenda",
    servicios: ROUTES_APP.app + ROUTES_APP.source + "/servicios",
    crm: ROUTES_APP.app + ROUTES_APP.source + "/crm",
    caja: ROUTES_APP.app + ROUTES_APP.source + "/caja",
    productividad: ROUTES_APP.app + ROUTES_APP.source + "/productividad",
    inventario: ROUTES_APP.app + ROUTES_APP.source + "/inventario",
    laboratorio: ROUTES_APP.app + ROUTES_APP.source + "/laboratorio",
    whattsap: ROUTES_APP.app + ROUTES_APP.source + "/whattsap",
    home: ROUTES_APP.app + ROUTES_APP.source + "/dashboard",
    perfil: ROUTES_APP.app + ROUTES_APP.source + "/perfil",
    medical: ROUTES_APP.app + ROUTES_APP.source + "/medical",
    mn_transfer_shown: ROUTES_APP.app + ROUTES_APP.source + "/ope-transfer",
    mn_transfer_list_shown: ROUTES_APP.app + ROUTES_APP.source + "/qry-transfer",
    mn_profile_shown: ROUTES_APP.app + ROUTES_APP.source + "/ope-profile",
    mn_profile_list_shown: ROUTES_APP.app + ROUTES_APP.source + "/qry-profile",
    mn_promotions_shown: `${ROUTES_APP.app}${ROUTES_APP.promotions}/ope-promo`,
    mn_promotions_list_shown: `${ROUTES_APP.app}${ROUTES_APP.promotions}/qry-promo`,
    mn_work_order_shown: ROUTES_APP.app + ROUTES_APP.source + "/workorder",

    mn_discount_shown: `${ROUTES_APP.app}${ROUTES_APP.discount}/ope-discount`,
    mn_discountv2_shown: `${ROUTES_APP.app}${ROUTES_APP.discount}/ope-discountv2`,
    mn_discount_list_shown: `${ROUTES_APP.app}${ROUTES_APP.discount}/qry-discount`,
    mn_discountv2_list_shown: `${ROUTES_APP.app}${ROUTES_APP.discount}/qry-discountv2`,

    mn_store_shown: ROUTES_APP.app + ROUTES_APP.source + "/ope-store",
    mn_store_list_shown: `${ROUTES_APP.app}${ROUTES_APP.source}/qry-store`,
    mn_store_user_shown: `${ROUTES_APP.app}${ROUTES_APP.source}/store-user`,
}
